### ISSUE TITLE
BlazorSplitter preview

### ISSUE THREAD

**Issue by emiliojoseav** [Lupusa87/BlazorSplitter#1]
Hi Vakhtangi, this is Emilio. from Presence Technology, Enghouse.
We need to use a spliter componente in our Blazor app, and we found your project, awesome work.

But we realiced that you are using a preview Blazor version, and unfortunatly it's not compatible with our app, that is made with "Microsoft.AspNetCore.Components 3.1.0"

Have you planing to migrate the project?

Best regards, Emilio.

**Comment by Lupusa87** [comment]
Hello Emilio,

Thank you for reaching out.

I just updated repo and nuget package to latest version.

Splitter component is class library targeting .netstandard 2.1

Microsoft.AspNetCore.Components Version="5.0.0-preview.5.20279.2"
Microsoft.AspNetCore.Components.Web Version="5.0.0-preview.5.20279.2"

It should be compatible to latest blazor bits.

I recommend to use nuget package
Install-Package BlazorSplitterComponent -Version 1.0.7

You can check demo [here](https://lupblazordemos.z13.web.core.windows.net/PageSplitter) with source [here](https://github.com/Lupusa87/LupusaBlazorDemos/blob/master/LupusaBlazorDemos/Demos/PageSplitter.razor) and [here](https://github.com/Lupusa87/LupusaBlazorDemos/blob/master/LupusaBlazorDemos/Demos/PageSplitter.razor.cs)

Please check it, hope it helps.

If you have any issue please feel free to contact me.

![Untitled](https://user-images.githubusercontent.com/40779557/84424976-d4dc6080-abee-11ea-9cfb-c74ece87cc55.png)

**Comment by Lupusa87** [comment]
I do not understand what you mean Blazor release version 4.7
Latest Blazor version is RTM and splitter works with it.
